name: CD

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.KEY }}
      - uses: tool3/bump@master
        id: bump
        with:
          github_token: ${{ secrets.KEY }}
          user: 'Versioning Action'
          email: 'versioning@github.com'
          branch: 'main'
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: 'Push images to ACR'
        run: |
          echo "${{ steps.bump.outputs.version }}"
          docker build . --tag ${{ secrets.ACR_LOGIN }}/numerouno:${{ steps.bump.outputs.version }} --tag ${{ secrets.ACR_LOGIN }}/numerouno:latest
          docker push ${{ secrets.ACR_LOGIN }}/numerouno:${{ steps.bump.outputs.version }}
          docker push ${{ secrets.ACR_LOGIN }}/numerouno:latest
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: number-one
          dns-name-label: nummer-een
          image: ${{ secrets.ACR_LOGIN }}/numerouno:${{ steps.bump.outputs.version }}
          registry-login-server: ${{ secrets.ACR_LOGIN }}
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          name: nummer-een
          location: 'central us'
