name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
jobs:
  build:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      run: |
        npm install
    - name: 'Build'
      run: |
        npm run build
    - name: 'Build Image'
      run: docker build .

  coverage:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      run: |
        npm install
    - name: 'Linting'
      run: |
        npm run lint
    - name: 'Run Tests'
      run: |
        npm run test
    - name: 'Code Coverage'
      run: |
        npm run coverage
